### ISSUE TITLE
Cannot get connection working

### ISSUE THREAD

**Issue by scrumthing** [bgregs514/vscode-tm1#14] opened 2021-03-02 07:07 UTC
**Describe the bug**
Cannot get connection working. What am I doing wrong? Maybe we should add a short description on how to connect. 

![vscodetm1_bug_connection01](https://user-images.githubusercontent.com/8442014/109611042-f0e1b280-7b2d-11eb-801d-954350581be8.PNG)

![vscodetm1_bug_connection02](https://user-images.githubusercontent.com/8442014/109611330-5df54800-7b2e-11eb-9194-d34e31ad78db.PNG)

**Comment by bgregs514** [comment] 2021-03-02 15:07
@scrumthing Good catch!  Looks like it's an issue with the default authentication case.  I have only tested in CAM and security mode 1, so this is a good test.  I haven't tried modifying the code yet, but we most likely either need to come up with a specific case 2, or drop the namespace from the default switch case here:

```typescript
	default:
		encodedCreds = "Negotiate " + Buffer.from(settings.get("username") + ":" + settings.get("password") + ":" + settings.get("namespace")).toString("base64");
```
I'm not sure if dropping the namespace impacts modes 3 and 4 though, so we may need to test.  I'm leaning towards an explicit case 2 defined, but open to other ideas.

**Comment by scrumthing** [comment] 2021-03-02 16:26
Sorry but it didn't work in mode 1 too.

**Comment by bgregs514** [comment] 2021-03-02 18:07
Security mode 2 should be fixed now - basically it just falls through to run as mode 1 as far as https authentication is concerned.

I was not able to reproduce mode 1 not working however.  My guess would be that you need to set mode 1, close the extension, open it in F5 debugger mode again, and then it should work - it worked for me this way at least.  I haven't implemented a "tree refresh" method yet, so the only way to force the new settings to take effect would be to close down and open up again - I really need to build that refresh method. 😉

**Comment by scrumthing** [comment] 2021-03-02 18:15
I wanted to suggest the same. Refresh tree and maybe something like a save button (which would basically be a refresh-button as well) because I think that would be easier for the user.

**Closed** 2021-03-02 20:13 UTC
