### ISSUE TITLE
Cannot start extension

### ISSUE THREAD

**Issue by scrumthing** [bgregs514/vscode-tm1#17] opened 2021-03-11 06:38 UTC
**Describe the bug**
The extension does not start. Instead I get the following error message

**Screenshots**
![image](https://user-images.githubusercontent.com/8442014/110746162-ac949780-823c-11eb-8628-1b2ea22a8303.png)

![image](https://user-images.githubusercontent.com/8442014/110746187-b74f2c80-823c-11eb-91be-4771501d3c0b.png)

**Comment by bgregs514** [comment] 2021-03-12 13:34
Interesting.  Usually an error similar to this will pop up when dependencies are missing from the node-modules folder.  Given that much of the folder structure has been changing with recent updates, is this still an issue after a fresh pull request?  Also, have you tried an npm install inside the root folder?

I'll be curious to see if anyone else is getting this error too - so far I have tested on 2 physical machines and 1 virtual machine and haven't been able to reproduce.

**Comment by ykud** [comment] 2021-03-13 21:55
I couldn't reproduce it on on my win 2012 server VM with a fresh install.
@scrumthing , what's your OS version?
Let me try to package the current build into vsix and maybe we try that as well?

**Comment by scrumthing** [comment] 2021-03-15 06:25
The error occurred after I pulled the newest version. 
Now I deleted the whole vscode-tm1 folder and did all steps again. Still the same error. 

I am on Windows 10 Enterprise 64bit. 

Open for any suggestions. :-)

**Comment by bgregs514** [comment] 2021-03-23 13:45
@scrumthing Are you still having an issue with the latest builds?  If not, I'll go ahead and close this one down.  Feel free to reach out if the issue persists!

**Comment by bgregs514** [comment] 2021-03-25 13:33
Closing - this should be fixed in the latest build.

**Closed by bgregs514** 2021-03-25 13:33 UTC
